### ISSUE TITLE
Cell Label Assignment?

### ISSUE THREAD

**Issue by mrland99** [zakieh-tayyebi/CellSpace#1]
I noticed after running CellSpace the cells were being assigned something like `__label__C7828`. I was wondering if it was possible to assign pre-existing labels either before or when running CellSpace so they would be carried over and I would know which cell corresponds to which label. If so, can you pinpoint where? I had trouble finding it. 

Thanks. Cool method by the way.

**Comment by zakieh-tayyebi** [comment]
Hi!
I actually haven’t added that. The cells will be in the same order as in the count matrix, and the R functions have the option to add cell names while reading the trained embedding matrix, downstream.
But I understand it would be more convenient to add it before that, so I’ll add the option!

Thank you,
Bests,
Zakieh.
________________________________
From: Max Land ***@***.***>
Sent: Thursday, June 16, 2022 5:33:05 PM
To: zakieh-tayyebi/CellSpace ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [zakieh-tayyebi/CellSpace] Cell Label Assignment? (Issue #1)


I noticed after running CellSpace the cells were being assigned something like __label__C7828. I was wondering if it was possible to assign pre-existing labels either before or when running CellSpace so they would be carried over and I would know which cell corresponds to which label. If so, can you pinpoint where? I had trouble finding it.

Thanks. Cool method by the way.

**Comment by mrland99** [comment]
Oh hmm, somehow my cell order got randomized before and after running CellSpace but I might have overlooked something on my part. 

But anyways, thanks for the quick response. Looking forward to exploring CellSpace more :)

**Comment by zakieh-tayyebi** [comment]
No problem!
The order in the embedding matrix might be random, but the number in the label is the correct index for the cells. For example, __label__C1 is the first cell of the count matrix.
The R function that creates the CellSpace object in R, orders them based on that number and then assigns the cell names you input.

Thank you,
Bests,
Zakieh.
________________________________
From: Max Land ***@***.***>
Sent: Thursday, June 16, 2022 6:08:16 PM
To: zakieh-tayyebi/CellSpace ***@***.***>
Cc: Zakieh Tayyebi ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [zakieh-tayyebi/CellSpace] Cell Label Assignment? (Issue #1)


Oh hmm, somehow my cell order got randomized before and after running CellSpace but I might have overlooked something on my part.

But anyways, thanks for the quick response. Looking forward to exploring CellSpace more.
