### ISSUE TITLE
clustering not recovering main cell types

### ISSUE THREAD

**Issue by Brawni** [zakieh-tayyebi/CellSpace#3]
Hello!

Thanks for this package!
I have run CellSpace using default parameters following your tutorial on the github page. Unfortunately when i then plot the results the umap only shows too large clusters with no evidence of separation of main cell types. To give you an idea im also attaching the clustering i get from ArchR. The umaps are colored by sample even though coloring is different. Once again, I would expect to see a highly structured umap (similar to the archr one) as each samples contain immune stromal and epithelial cells (tumors).
Let me know if you have an idea of what's happening here and if you need other info!

Thanks so much!

<img width="445" alt="image" src="https://github.com/zakieh-tayyebi/CellSpace/assets/58828216/60863225-79a5-4261-ab23-47c271ad3e25">
<img width="499" alt="image" src="https://github.com/zakieh-tayyebi/CellSpace/assets/58828216/123f481d-43c2-46c8-91c1-28eec3430706">

**Comment by zakieh-tayyebi** [comment]
Thank you for using CellSpace and I'm sorry that you're having issues with the results!
A few questions:
- Is the structure of the CellSpace embedding completely wrong, or just that the clusters are not separated on the UMAP? Have you tried changing the spread/min-dist for UMAP and increasing resolution of clustering?
- What is the number of cells and peaks/tiles that you're using for input? Are you using the variable tiles from ArchR? Does the embedding improve with more epochs?

**Comment by Brawni** [comment]
Hi Zakieh, 

thanks for getting in touch! To answer your questions: The embedding looked completely wrong as cell markers using genescore show random distributions.
Im using 25,000 most variable peaks outputted from ArchR. 
I run it again using 100epochs and now it looks improved as i can see more structure and markers light up indifferent areas! (see umaps attached) However I'm still looking to recover more structure as the data should contain malignant cells as well as normal ones which i dont see separating for now. That said sample batchiness is completely removed so that looks cool! Should i keep increasing epochs? I will start tuning the UMAP parameters too and let you know. 

I'm reporting also a bug in ArchR that may be headachy downstream. The barcodes order are NOT the same in the tile matrix compared to the ArchR object, so any barcode annotation will have to be re-indexed.

 
<img width="1419" alt="image" src="https://github.com/zakieh-tayyebi/CellSpace/assets/58828216/958e6c40-f897-482f-9a55-3a64057a5d94">

 
Thanks !!

**Comment by zakieh-tayyebi** [comment]
That is strange because, in my experience, CellSpace finds the right general structure even if there is not enough separation between cell types. 100 epochs should be more than enough, even for bigger datasets!

Is it possible that the order of cells is wrong?
The order of cells in 'meta.data' or 'cell.names' that you provide (to create the CellSpace object in R) should be the same as the order of cells in the count matrix (to train the CellSpace model).

The cells are labelled as __label__C1, ..., __label__Cn in the trained model (.tsv file), with the same order as in the count matrix. In the future, we will use unique cell names so the order would not matter!

**Comment by Brawni** [comment]
With 100 epochs I do see coarse separation of different cell lineages as shown by the UMAP I posted showing expression of cell type markers. However, this grade of separation is still insufficient to distinguish malignant from normal cells. I tried re-running with 200 epochs, playing with spread parameter and also increasing the variable features to 200k but the results dont look much different from previous iteration. Any other suggestions on how to improve separation of cell types?

**Comment by Brawni** [comment]
I was thinking to run the UMAP only on epithelial cells. Is there a way to subset a cellSpace object?

**Comment by zakieh-tayyebi** [comment]
Sorry that you're still having issues! I really don't think you need to run 200 epochs.
Have you tried using a higher number of events, for example 50K top variable tiles?

You can compute UMAP using the embedding of a subset of cells:
`run_UMAP(object, emb = object@cell.emb[subset.index, ], name = "subsetCells_UMAP")`
In the next version of CellSpace, I'm going to use the SingleCellExperiment class so features like subsetting would be easy to do.
