### ISSUE TITLE
Application to scRNA-seq dataset?

### ISSUE THREAD

**Issue by LiuCanidk** [zakieh-tayyebi/CellSpace#5]
Hi, I have just browsed the elegant manuscript and appreciated the idea of integrating the sequence information!

I'm just curious about the application to the scRNA-seq dataset, to also integrate the sequence information to achieve better embeddings for downstream analysis, also importantly for removing batch effect.

Is that possible? Have the development team ever considered this before?

Any reply is greatly appreciated!

**Comment by z-tayyebi** [comment]
We have never tried integrating RNA sequence information, but that is certainly something we've considered as an extension to CellSpace!

**Comment by LiuCanidk** [comment]
Thanks, looking forward to this promising extension!






---- Replied Message ----
| From | Zakieh ***@***.***> |
| Date | 5/10/2024 10:35 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [zakieh-tayyebi/CellSpace] Application to scRNA-seq dataset? (Issue #5) |

We have never tried integrating RNA sequence information, but that is certainly something we've considered as an extension to CellSpace!
